# Generated by Django 5.0 on 2024-01-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='desciption',
            field=models.CharField(default='none', max_length=1000),
        ),
    ]
