# Generated by Django 5.0 on 2024-01-02 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0004_menuitem_desciption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='desciption',
            new_name='description',
        ),
    ]
